name: Vividus CI

on:
  push:
    branches:
    - master
    tags:
    - release-[0-9]+.[0-9]+.[0-9]+
    paths:
      - '**/**'
      - '!docs/**'
      - '!*.md'
  pull_request:
    branches:
    - master
    paths:
      - '**/**'
      - '!docs/**'
      - '!*.md'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout (including submodules and tags)
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache ~/.gradle/wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('vividus-build-system/**/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper-

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 16

    - name: Build
      env:
        MATRIX_PLATFORM: ${{ matrix.platform }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: bash
      run: |
        if [[ $MATRIX_PLATFORM = "ubuntu-latest" ]]; then
          if [[ -n $SONAR_TOKEN ]]; then
            ./gradlew clean build sonarqube -Dsonar.host.url=https://sonarcloud.io \
                                      -Dsonar.organization=vividus \
                                      -Dsonar.projectKey=vividus-framework_vividus \
                                      -Dorg.gradle.jvmargs="-Xmx1g -XX:MaxMetaspaceSize=768m" \
                                      -Ptest.testLogging.exceptionFormat=full \
                                      -i
          else
            echo No SONAR_TOKEN, SonarQube analysis will be skipped
            ./gradlew build -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=768m" \
                            -Ptest.testLogging.exceptionFormat=full
          fi
        else
          ./gradlew clean build -x spotbugsMain -x spotbugsTest -x spotbugsIntegrationTest \
                          -x pmdMain -x pmdTest -x pmdIntegrationTest \
                          -Ptest.testLogging.exceptionFormat=full --no-daemon -i -Dorg.gradle.jvmargs="-Xmx1g -XX:MaxMetaspaceSize=768m"
        fi
